repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.356
    hooks:
      - id: ruff
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
-   repo: https://github.com/rhysd/actionlint
    rev: v1.6.29
    hooks:
      - id: actionlint
        args: [".github/workflows"]
-   repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: ["--config-file=.yamllint.yaml"]
